pub mod string_permutation;
pub mod permutations;
pub mod first_permutation_is_substr_of_second_str;
pub mod combination_sum;
pub mod generate_parentheses;
pub mod phone_number_mnemonics;
pub mod powerset;
pub mod unique_path_iii;
pub mod word_search;